// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrzwslnaebtcfkelbwft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyendzbG5hZWJ0Y2ZrZWxid2Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NjEzNTIsImV4cCI6MjA3MjMzNzM1Mn0.2DkPFVQvdfd_JDARAjA0x8XIvMRDBtawP7A1CRK_obQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});